export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_ACCOUNT_REQUEST = 'ORDER_ACCOUNT_REQUEST';
export const ORDER_ACCOUNT_SUCCESS = 'ORDER_ACCOUNT_SUCCESS';
export const ORDER_ACCOUNT_FAIL = 'ORDER_ACCOUNT_FAIL';
export const ORDER_ACCOUNT_RESET = 'ORDER_ACCOUNT_RESET';

export const ORDER_CANCEL_SUCCESS = 'ORDER_CANCEL_SUCCESS';
export const ORDER_CANCEL_RESET = 'ORDER_CANCEL_RESET';
