export const SANPHAM_LIST_REQUEST = 'SANPHAM_LIST_REQUEST';
export const SANPHAM_LIST_SUCCESS = 'SANPHAM_LIST_SUCCESS';
export const SANPHAM_LIST_FAIL = 'SANPHAM_LIST_FAIL';

export const SANPHAM_DETAILS_REQUEST = 'SANPHAM_DETAILS_REQUEST';
export const SANPHAM_DETAILS_SUCCESS = 'SANPHAM_DETAILS_SUCCESS';
export const SANPHAM_DETAILS_FAIL = 'SANPHAM_DETAILS_FAIL';
export const SANPHAM_DETAILS_RESET = 'SANPHAM_DETAILS_RESET';

export const SANPHAM_REVIEW_REQUEST = 'SANPHAM_REVIEW_REQUEST';
export const SANPHAM_REVIEW_SUCCESS = 'SANPHAM_REVIEW_SUCCESS';
export const SANPHAM_REVIEW_FAIL = 'SANPHAM_REVIEW_FAIL';
export const SANPHAM_REVIEW_RESET = 'SANPHAM_REVIEW_RESET';

export const SANPHAM_RELATED_REQUEST = 'SANPHAM_RELATED_REQUEST';
export const SANPHAM_RELATED_SUCCESS = 'SANPHAM_RELATED_SUCCESS';
export const SANPHAM_RELATED_FAIL = 'SANPHAM_RELATED_FAIL';

export const SANPHAM_COLOR_SUCCESS = 'SANPHAM_COLOR_SUCCESS';
export const SANPHAM_SIZE_SUCCESS = 'SANPHAM_SIZE_SUCCESS';
