export const TAIKHOAN_LOGIN_REQUEST = 'TAIKHOAN_LOGIN_REQUEST';
export const TAIKHOAN_LOGIN_SUCCESS = 'TAIKHOAN_LOGIN_SUCCESS';
export const TAIKHOAN_LOGIN_FAIL = 'TAIKHOAN_LOGIN_FAIL';

export const TAIKHOAN_LOGOUT = 'TAIKHOAN_LOGOUT';

export const TAIKHOAN_REGISTER_REQUEST = 'TAIKHOAN_REGISTER_REQUEST';
export const TAIKHOAN_REGISTER_SUCCESS = 'TAIKHOAN_REGISTER_SUCCESS';
export const TAIKHOAN_REGISTER_FAIL = 'TAIKHOAN_REGISTER_FAIL';

export const TAIKHOAN_PROFILE_REQUEST = 'TAIKHOAN_PROFILE_REQUEST';
export const TAIKHOAN_PROFILE_SUCCESS = 'TAIKHOAN_PROFILE_SUCCESS';
export const TAIKHOAN_PROFILE_FAIL = 'TAIKHOAN_PROFILE_FAIL';
export const TAIKHOAN_PROFILE_RESET = 'TAIKHOAN_PROFILE_RESET';

export const TAIKHOAN_PROFILE_UPDATE_REQUEST = 'TAIKHOAN_PROFILE_UPDATE_REQUEST';
export const TAIKHOAN_PROFILE_UPDATE_SUCCESS = 'TAIKHOAN_PROFILE_UPDATE_SUCCESS';
export const TAIKHOAN_PROFILE_UPDATE_FAIL = 'TAIKHOAN_PROFILE_UPDATE_FAIL';
export const TAIKHOAN_PROFILE_UPDATE_RESET = 'TAIKHOAN_PROFILE_UPDATE_RESET';
